/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreTopicRouteImport } from './routes/explore.$topic'

const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTopicRoute = ExploreTopicRouteImport.update({
  id: '/explore/$topic',
  path: '/explore/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/history': typeof HistoryRoute
  '/score': typeof ScoreRoute
  '/explore/$topic': typeof ExploreTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/history': typeof HistoryRoute
  '/score': typeof ScoreRoute
  '/explore/$topic': typeof ExploreTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/history': typeof HistoryRoute
  '/score': typeof ScoreRoute
  '/explore/$topic': typeof ExploreTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/achievements' | '/history' | '/score' | '/explore/$topic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/achievements' | '/history' | '/score' | '/explore/$topic'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/history'
    | '/score'
    | '/explore/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  HistoryRoute: typeof HistoryRoute
  ScoreRoute: typeof ScoreRoute
  ExploreTopicRoute: typeof ExploreTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$topic': {
      id: '/explore/$topic'
      path: '/explore/$topic'
      fullPath: '/explore/$topic'
      preLoaderRoute: typeof ExploreTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  HistoryRoute: HistoryRoute,
  ScoreRoute: ScoreRoute,
  ExploreTopicRoute: ExploreTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
